config/routes.rb
Mthost::Application.routes.draw do
  resources :shift_logs
  devise_for :users

  resources :users
  resources :mail
  resources :shift_types
  resources :shifts
  resources :shift_collections
  resources :galleries
  resources :exports
  resources :sys_configs
  resources :reports
  resources :pages
  resources :host_haulers, only: [:index]
  resources :ongoing_trainings
  resources :training_dates
  resources :ongoing_trainings

  get '/download_end_of_year', :to =>  "exports#eoy_download"
  get '/export/shift_summary/:year', :to =>  "exports#shift_summary_download"
  get '/hosts_by_seniority', :to => 'users#hosts_by_seniority'
  get '/hosts_by_seniority_export', :to => 'reports#hosts_by_seniority_export' # only used with csv suffix
  get '/hosts_by_roles', :to => 'users#hosts_by_roles'
  get '/shifts_by_date', :to => 'shifts#shifts_by_date_view'
  get '/skipatrol', :to => "reports#skipatrol"
  post '/skipatrol', :to => "reports#skipatrol"
  get '/skipatrol_printable', :to => "reports#skipatrol_printable"

  get '/duties_report', :to => 'reports#duties_report'
  post '/duties_report', :to => 'reports#duties_report'
  get '/duties_printable', :to => "reports#duties_printable"
  get '/hauler_drivers_report', :to => "reports#hauler_drivers_report"

  get '/shift_print/:id', :to => 'users#shift_print'
  post '/users/save_new', :to => 'users#save_new'
  post '/shifts/assign_team_leaders', :to => 'shifts#assign_team_leaders'
  get '/assign_team_leaders', :to => 'shifts#edit_team_leader_shifts'

  # EMAIL STUFF
  get 'send_shift_reminder_email', :to => "mail#send_shift_reminder_email"
  get '/select_hosts_for_email', :to => "mail#select_hosts_for_email"

  get '/send_custom_mail', :to => "mail#send_custom_mail"
  post '/send_custom_mail', :to => "mail#send_custom_mail"
  post '/deliver_mail', :to => "mail#deliver_mail"
  get '/send_mail/:address', :to => "mail#send_mail"
  get '/send_mail/hauler/:hauler_id', :to => 'mail#send_hauler_mail'


  get '/show_contact_info', :to => "pages#show_contact_info"

  get '/set_start_year/:year', :to => "users#set_start_year"
  get '/clear_assignments', :to => "users#clear_assignments"
  get '/delete_shifts', :to => "shifts#delete_shifts"
  get '/delete_hauler_entries', :to => "host_haulers#delete_all_entries"
  get '/reset_confirms_and_passwords', :to => "users#reset_confirms_and_passwords"
  get '/init_confirmations', :to => "users#init_confirmations"
  get '/init_meetings', :to => "users#init_meetings"


  post '/set_user_active/:value', :to => "users#set_user_active"

  get '/drop_shift/:id', :to => 'shifts#drop_shift'
  get '/select_shift/:id', :to => 'shifts#select_shift'
  # get '/disable_shift/:id', :to => 'shifts#toggle_shift_disabled' #'shifts#disable_shift'
  # get '/enable_shift/:id', :to => 'shifts#toggle_shift_disabled' #'shifts#enable_shift'
  # get '/toggle_shift_disabled/:id', :to => 'shifts#toggle_shift_disabled'
  post '/toggle_shift_disabled/:value', :to => 'shifts#toggle_shift_disabled'

  get '/ghost_user/:id', :to => 'users#ghost_user'
  get '/un_ghost_user', :to => 'users#un_ghost_user'

  get "shift_logs/by_shift/:shift_id", :to => 'shift_logs#by_shift'
  get "shift_logs/by_user/:user_id", :to => 'shift_logs#by_user'

  get '/hauler_scheduler/:hauler_id', :to => 'host_haulers#scheduler'

  get '/drop_driver/:id', :to => 'host_haulers#drop_driver'
  get '/select_driver/:id', :to => 'host_haulers#select_driver'

  get '/drop_rider/:rider_id', :to => 'host_haulers#drop_rider'
  get '/select_rider/:rider_id', :to => 'host_haulers#select_rider'
  get '/export_hauler/:hauler_id', :to =>  "exports#host_hauler_download"
  get '/set_rider_to_host/:rider_id', :to => 'host_haulers#set_rider_to_host'
  post '/update_rider_in_hauler', :to => 'host_haulers#update_rider_in_hauler'
  get '/set_driver_to_host/:hauler_id', :to => 'host_haulers#set_driver_to_host'
  post '/update_driver_in_hauler', :to => 'host_haulers#update_driver_in_hauler'
  get '/add_hauler/:date_value', :to => 'host_haulers#add_hauler'
  get '/hauler_scheduler', :to => 'host_haulers#scheduler'
  get '/delete_hauler/:hauler_id', :to => 'host_haulers#delete_hauler'
  get '/drop_ongoing_training/:id', :to => 'ongoing_trainings#drop_shift'
  get '/select_ongoing_training', :to => 'ongoing_trainings#select_ongoing_training'
  post '/make_ongoing_training_selection/:is_trainer/:id', :to => 'ongoing_trainings#make_ongoing_training_selection'

  # catchall route to get pages
  get "/:id" => "pages#show"
  root :to => "pages#show"
end

app/models/shift_log.rb
# == Schema Information
#
# Table name: shift_logs
#
#  id           :integer          not null, primary key
#  change_date  :datetime
#  user_id      :integer
#  shift_id     :integer
#  action_taken :string
#  note         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ShiftLog < ActiveRecord::Base
  belongs_to :user
  belongs_to :shift

  def shift_info
    if action_taken.include? 'OGOMt Training'
      "OGOMt Training Shift: see notes."
    else
      if self.shift.nil?
        "#{self.shift_id}:DELETED SHIFT - see notes"
      else
        "#{self.shift_id}:#{self.shift.shift_date.strftime("%Y-%m-%d")}:#{self.shift.short_name}"
      end
    end
  end
end

app/controllers/shift_logs_controller.rb
# == Schema Information
#
# Table name: shift_logs
#
#  id           :integer          not null, primary key
#  change_date  :datetime
#  user_id      :integer
#  shift_id     :integer
#  action_taken :string
#  note         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ShiftLogsController < ApplicationController
  authorize_resource
  before_action :set_shift_log, only: [:show, :edit, :update, :destroy]

  # GET /shift_logs
  # GET /shift_logs.json
  def index
    if current_user.has_role? :admin
      @shift_logs = ShiftLog.all.order(change_date: :desc)
      @date_value = nil
    else
      @shift_logs = []
      flash[:alert] = "Access To Logs Denied"
      redirect_to root_path
    end
  end

  # GET /shift_logs/1
  # GET /shift_logs/1.json
  def show
    unless current_user.has_role? :admin
      flash[:alert] = "Access To Logs Denied"
      redirect_to root_path
    end
  end

  # GET /shift_logs/new
  def new
    if current_user.has_role? :admin
      @shift_log = ShiftLog.new
    else
      @shift_log = nil
      flash[:alert] = "Access To Logs Denied"
      redirect_to root_path
    end
  end

  # GET /shift_logs/1/edit
  def edit
    unless current_user.has_role? :admin
      flash[:alert] = "Access To Logs Denied"
      redirect_to root_path
    end
  end

  # POST /shift_logs
  # POST /shift_logs.json
  def create
    if current_user.has_role? :admin
      @shift_log = ShiftLog.new(shift_log_params)

      respond_to do |format|
        if @shift_log.save
          format.html {redirect_to @shift_log, notice: 'Shift log was successfully created.'}
          format.json {render :show, status: :created, location: @shift_log}
        else
          format.html {render :new}
          format.json {render json: @shift_log.errors, status: :unprocessable_entity}
        end
      end
    else
      flash[:alert] = "Access To Logs Denied"
      redirect_to root_path
    end
  end

  # PATCH/PUT /shift_logs/1
  # PATCH/PUT /shift_logs/1.json
  def update
    if current_user.has_role? :admin
      respond_to do |format|
        if @shift_log.update(shift_log_params)
          format.html {redirect_to @shift_log, notice: 'Shift log was successfully updated.'}
          format.json {render :show, status: :ok, location: @shift_log}
        else
          format.html {render :edit}
          format.json {render json: @shift_log.errors, status: :unprocessable_entity}
        end
      end
    else
      flash[:alert] = "Access To Logs Denied"
      redirect_to root_path
    end
  end

  # DELETE /shift_logs/1
  # DELETE /shift_logs/1.json
  def destroy
    if current_user.has_role? :admin
      @shift_log.destroy
      respond_to do |format|
        format.html {redirect_to shift_logs_url, notice: 'Shift log was successfully destroyed.'}
        format.json {head :no_content}
      end
    else
      flash[:alert] = "Access To Logs Denied"
      redirect_to root_path
    end
  end

  def by_shift
    if current_user.has_role? :admin
      @shift_logs = ShiftLog.where(shift_id: params[:shift_id]).order(updated_at: :asc)
    else
      @shift_logs = []
      flash[:alert] = "Access To Logs Denied"
      redirect_to root_path
    end
  end

  def by_user
    if current_user.has_role? :admin
      @shift_logs = ShiftLog.where(user_id: params[:user_id]).order(updated_at: :asc)
    else
      @shift_logs = []
      flash[:alert] = "Access To Logs Denied"
      redirect_to root_path
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_shift_log
    @shift_log = ShiftLog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shift_log_params
    params.require(:shift_log).permit(:change_date, :user_id, :shift_id, :action_taken, :note)
  end
end

app/helpers/shift_logs_helper.rb
# == Schema Information
#
# Table name: shift_logs
#
#  id           :integer          not null, primary key
#  change_date  :datetime
#  user_id      :integer
#  shift_id     :integer
#  action_taken :string
#  note         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

module ShiftLogsHelper
end

app/views/shift_logs/_form.html.erb
<%= form_for(@shift_log) do |f| %>
  <% if @shift_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shift_log.errors.count, "error") %> prohibited this shift_log from being saved:</h2>

      <ul>
      <% @shift_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :change_date %><br>
    <%= f.text_field :change_date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :shift_id %><br>
    <%= f.text_field :shift_id %>
  </div>
  <div class="field">
    <%= f.label :action_taken %><br>
    <%= f.text_field :action_taken %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shift_logs/_index_body.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Change date</th>
    <th>User</th>
    <th>Shift</th>
    <th>Action taken</th>
    <th>Note</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @shift_logs.each do |shift_log| %>
  <% if @date_value != shift_log.change_date.strftime("%Y-%m-%d") %>
    <tr>
      <td colspan="8">>>>>>>>  DATE: <%= shift_log.change_date.strftime("%Y-%m-%d") %></td>
    </tr>
    <% @date_value = shift_log.change_date.strftime("%Y-%m-%d") %>
  <% end %>

      <tr>
        <td><%= shift_log.change_date.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= shift_log.user.name %></td>
        <td><%= shift_log.shift_info %></td>
        <td><%= shift_log.action_taken %></td>
        <td><%= shift_log.note %></td>

        <td>
          <a href="<%= "#{shift_logs_path}/#{shift_log.id}" %>" class='btn btn-primary btn-small'>
            <i class='icon-search icon-large icon-white'></i>
          </a>
        </td>
        <td>
          <a href="<%= edit_shift_log_path(shift_log) %>" class='btn btn-warning btn-small'>
            <i class='icon-wrench icon-large icon-white'></i>
          </a>
        </td>
        <td>
          <%= link_to "<i class='icon-trash icon-large icon-white'".html_safe,
                      shift_log, method: :delete,
                      data: { confirm: 'Are you sure?' },
                      class: 'btn btn-danger btn-small' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/shift_logs/by_shift.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shift Logs By Shift</h1>
<%= link_to "Shift Index", shifts_path, class: "btn btn-small btn-success" %>


<%= render "index_body" %>

app/views/shift_logs/by_user.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shift Logs By User</h1>
<%= link_to "User Index", users_path, class: "btn btn-small btn-success" %>

<%= render "index_body" %>

app/views/shift_logs/edit.html.erb
<h1>Editing Shift Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift_log %> |
<%= link_to 'Back', shift_logs_path %>

app/views/shift_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shift Logs (<%= @shift_logs.count %>)</h1>

<%= render "index_body" %>
<br>

<%= link_to "NEW", new_shift_log_path, class: 'btn btn-success btn-small' %>
<br/><br/>

app/views/shift_logs/new.html.erb
<h1>New Shift Log</h1>

<%= render 'form' %>

<%= link_to 'Back', shift_logs_path %>

app/views/shift_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Change date:</strong>
  <%= @shift_log.change_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @shift_log.user_id %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @shift_log.shift_id %>
</p>

<p>
  <strong>Action taken:</strong>
  <%= @shift_log.action_taken %>
</p>

<p>
  <strong>Note:</strong>
  <%= @shift_log.note %>
</p>

<%= link_to 'Edit', edit_shift_log_path(@shift_log) %> |
<%= link_to 'Back', shift_logs_path %>