config/routes.rb
Mthost::Application.routes.draw do
  resources :shift_logs
  devise_for :users

  resources :users
  resources :mail
  resources :shift_types
  resources :shifts
  resources :shift_collections
  resources :galleries
  resources :exports
  resources :sys_configs
  resources :reports
  resources :pages
  resources :host_haulers, only: [:index]
  resources :ongoing_trainings
  resources :training_dates
  resources :ongoing_trainings

  get '/download_end_of_year', :to =>  "exports#eoy_download"
  get '/export/shift_summary/:year', :to =>  "exports#shift_summary_download"
  get '/hosts_by_seniority', :to => 'users#hosts_by_seniority'
  get '/hosts_by_seniority_export', :to => 'reports#hosts_by_seniority_export' # only used with csv suffix
  get '/hosts_by_roles', :to => 'users#hosts_by_roles'
  get '/shifts_by_date', :to => 'shifts#shifts_by_date_view'
  get '/skipatrol', :to => "reports#skipatrol"
  post '/skipatrol', :to => "reports#skipatrol"
  get '/skipatrol_printable', :to => "reports#skipatrol_printable"

  get '/duties_report', :to => 'reports#duties_report'
  post '/duties_report', :to => 'reports#duties_report'
  get '/duties_printable', :to => "reports#duties_printable"
  get '/hauler_drivers_report', :to => "reports#hauler_drivers_report"

  get '/shift_print/:id', :to => 'users#shift_print'
  post '/users/save_new', :to => 'users#save_new'
  post '/shifts/assign_team_leaders', :to => 'shifts#assign_team_leaders'
  get '/assign_team_leaders', :to => 'shifts#edit_team_leader_shifts'

  # EMAIL STUFF
  get 'send_shift_reminder_email', :to => "mail#send_shift_reminder_email"
  get '/select_hosts_for_email', :to => "mail#select_hosts_for_email"

  get '/send_custom_mail', :to => "mail#send_custom_mail"
  post '/send_custom_mail', :to => "mail#send_custom_mail"
  post '/deliver_mail', :to => "mail#deliver_mail"
  get '/send_mail/:address', :to => "mail#send_mail"
  get '/send_mail/hauler/:hauler_id', :to => 'mail#send_hauler_mail'


  get '/show_contact_info', :to => "pages#show_contact_info"

  get '/set_start_year/:year', :to => "users#set_start_year"
  get '/clear_assignments', :to => "users#clear_assignments"
  get '/delete_shifts', :to => "shifts#delete_shifts"
  get '/delete_hauler_entries', :to => "host_haulers#delete_all_entries"
  get '/reset_confirms_and_passwords', :to => "users#reset_confirms_and_passwords"
  get '/init_confirmations', :to => "users#init_confirmations"
  get '/init_meetings', :to => "users#init_meetings"


  post '/set_user_active/:value', :to => "users#set_user_active"

  get '/drop_shift/:id', :to => 'shifts#drop_shift'
  get '/select_shift/:id', :to => 'shifts#select_shift'
  # get '/disable_shift/:id', :to => 'shifts#toggle_shift_disabled' #'shifts#disable_shift'
  # get '/enable_shift/:id', :to => 'shifts#toggle_shift_disabled' #'shifts#enable_shift'
  # get '/toggle_shift_disabled/:id', :to => 'shifts#toggle_shift_disabled'
  post '/toggle_shift_disabled/:value', :to => 'shifts#toggle_shift_disabled'

  get '/ghost_user/:id', :to => 'users#ghost_user'
  get '/un_ghost_user', :to => 'users#un_ghost_user'

  get "shift_logs/by_shift/:shift_id", :to => 'shift_logs#by_shift'
  get "shift_logs/by_user/:user_id", :to => 'shift_logs#by_user'

  get '/hauler_scheduler/:hauler_id', :to => 'host_haulers#scheduler'

  get '/drop_driver/:id', :to => 'host_haulers#drop_driver'
  get '/select_driver/:id', :to => 'host_haulers#select_driver'

  get '/drop_rider/:rider_id', :to => 'host_haulers#drop_rider'
  get '/select_rider/:rider_id', :to => 'host_haulers#select_rider'
  get '/export_hauler/:hauler_id', :to =>  "exports#host_hauler_download"
  get '/set_rider_to_host/:rider_id', :to => 'host_haulers#set_rider_to_host'
  post '/update_rider_in_hauler', :to => 'host_haulers#update_rider_in_hauler'
  get '/set_driver_to_host/:hauler_id', :to => 'host_haulers#set_driver_to_host'
  post '/update_driver_in_hauler', :to => 'host_haulers#update_driver_in_hauler'
  get '/add_hauler/:date_value', :to => 'host_haulers#add_hauler'
  get '/hauler_scheduler', :to => 'host_haulers#scheduler'
  get '/delete_hauler/:hauler_id', :to => 'host_haulers#delete_hauler'
  get '/drop_ongoing_training/:id', :to => 'ongoing_trainings#drop_shift'
  get '/select_ongoing_training', :to => 'ongoing_trainings#select_ongoing_training'
  post '/make_ongoing_training_selection/:is_trainer/:id', :to => 'ongoing_trainings#make_ongoing_training_selection'

  # catchall route to get pages
  get "/:id" => "pages#show"
  root :to => "pages#show"
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  street                 :string(255)
#  city                   :string(255)
#  state                  :string(255)
#  zip                    :string(255)
#  home_phone             :string(255)
#  cell_phone             :string(255)
#  alt_email              :string(255)
#  start_year             :integer
#  notes                  :text
#  confirmed              :boolean
#  active_user            :boolean
#  nickname               :string(255)
#  snowbird_start_year    :integer
#  head_shot              :string(255)
#

class UsersController < ApplicationController
  require "json"

  respond_to :html, :json, :js
  load_and_authorize_resource

  def get_survey_users
    users = User.active_users
    users.map do |u|
      name_array = u.name.split(' ')
      u.name = "#{name_array[-1]}, #{name_array[0..-2].join(' ')}"
    end
    @hosts = users.sort { |a, b| a.name <=> b.name }.map { |u| {name: u.name, id: u.id}}
    respond_with @hosts
  end

  def index
    if current_user.has_role? :admin
      @inactive_users = User.includes(:shifts).includes(:roles).inactive_users
    end
    @users = User.includes(:shifts).includes(:roles).active_users
    @users = @users.sort {|a,b| a.name <=> b.name }
  end

  def hosts_by_seniority
    # @users = User.includes(:shifts).active_users.order(:name).to_a.delete_if { |u| u.supervisor? || u.is_max? }
    # @rookies = User.rookies.includes(:roles).order(:name)
    # @freshmen =  User.group3.includes(:roles).order(:name).to_a.delete_if { |u| u.team_leader? }
    # @junior =  User.group2.includes(:roles).order(:name).to_a.delete_if { |u| u.team_leader? }
    # @senior =  User.group1.includes(:roles).order(:name).to_a.delete_if { |u| u.team_leader? }.delete_if {|u| u.supervisor? }
    # @leaders =  User.active_users.order(:name).to_a.delete_if { |u| !u.team_leader? }.delete_if {|u| u.supervisor? }
    # @trainers = User.active_users.order(:name).to_a.delete_if { |u| !u.has_role? :trainer}.delete_if {|u| u.supervisor? }
    # @surveyors = User.active_users.order(:name).to_a.delete_if { |u| !u.has_role? :surveyor}.delete_if {|u| u.supervisor? }
    # @missing =  @users - (@rookies + @freshmen + @junior + @senior + @leaders)
    # @admin_and_supervisors = User.includes(:shifts).active_users.order(:name).to_a.delete_if { |u| !u.supervisor? && !u.is_max? }

    @users = User.includes(:shifts).active_users.order(:name).to_a.delete_if { |u| u.supervisor? || u.is_max? }
    @rookies = User.rookies.includes(:roles).order(:name).to_a.delete_if { |u| u.supervisor? || u.is_max? }
    @freshmen =  User.group3.includes(:roles).order(:name).to_a.delete_if { |u| u.team_leader? }.delete_if { |u| u.supervisor? || u.is_max? }
    @junior =  User.group2.includes(:roles).order(:name).to_a.delete_if { |u| u.team_leader? }.delete_if { |u| u.supervisor? || u.is_max? }
    @senior =  User.group1.includes(:roles).order(:name).to_a.delete_if { |u| u.team_leader? }.delete_if { |u| u.supervisor? || u.is_max? }
    @leaders =  User.active_users.order(:name).to_a.delete_if { |u| !u.team_leader? }.delete_if { |u| u.supervisor? || u.is_max? }
    @trainers = User.active_users.order(:name).to_a.delete_if { |u| !u.has_role? :trainer}.delete_if { |u| u.supervisor? || u.is_max? }
    @admin_and_supervisors = User.includes(:shifts).active_users.order(:name).to_a.delete_if { |u| !u.admin? }
    @drivers = User.active_users.order(:name).to_a.delete_if { |u| !u.driver? }.delete_if { |u| u.supervisor? || u.is_max? }
    @missing =  @users - (@rookies + @freshmen + @junior + @senior + @leaders)


    # @ogom_trainers = User.active_users.order(:name).to_a.delete_if { |u| !u.has_role? :ongoing_trainer}.delete_if { |u| u.supervisor? }
    @inactive_users = User.inactive_users
  end

  def hosts_by_roles
    @users = User.includes(:shifts, :roles).active_users.order(:name).to_a

    @leaders =  User.includes(:shifts).active_users.order(:name).to_a.delete_if {|u| !u.team_leader? }.delete_if {|u| u.supervisor? }
    @drivers = User.includes(:shifts).active_users.order(:name).to_a.delete_if { |u| !u.driver? }
    @trainers = User.includes(:shifts).active_users.order(:name).to_a.delete_if {|u| !u.has_role? :trainer}.delete_if {|u| u.supervisor? }
    @surveyors = User.includes(:shifts).active_users.order(:name).to_a.delete_if {|u| !u.has_role? :surveyor}.delete_if {|u| u.supervisor? }
    @admins = User.includes(:shifts).active_users.order(:name).to_a.delete_if {|u| !u.has_role? :admin}
    @ogom_trainers = User.active_users.order(:name).to_a.delete_if {|u| !u.has_role? :ongoing_trainer}.delete_if {|u| u.supervisor? }.delete_if {|u| u.supervisor? }
    @inactive_users = User.inactive_users

    @regular = @users - (@leaders + @trainers + @surveyors + @admins)
  end

  def show

  end

  def edit
    @user = User.find(params[:id])
    @user.password = ''
  end

  def new
    @user = User.new
    @user.start_year = HostConfig.season_year
    @user.active_user = true
  end

  def destroy
    if User.destroy(params[:id])
      redirect_to users_path, notice: "User deleted"
    else
      redirect_to users_path, alert: "Unable to Delete User: #{@user.errors.messages}"
    end
  end

  def update
    is_conf_page =  (params[:user][:page_type] == 'confirmation_page')
    if is_conf_page && params[:user][:password].blank? && !(current_user.has_role? :admin)
      redirect_to :back, :alert => "You must set your password when confirming your information"
    elsif is_conf_page && params[:user][:password] == DEFAULT_PASSWORD
      redirect_to :back, :alert => "You cannot use the default password..."
    else
      params[:user].except!(:page_type)
      if params[:user][:password].blank?
        params[:user].except!(:password)
        params[:user].except!(:password_confirmation)
      end
      if !@user.update_attributes(params[:user])
        redirect_to :back, :alert => "Error saving user: #{@user.errors.messages}"
      else
        process_user_roles params

        if is_conf_page
          sign_in(@user, bypass: true)
          redirect_to root_path
        else
          redirect_to user_path(@user.id)
        end
      end
    end
  end

  def create
    @user = User.create(params[:user])
    if @user.id.nil?
      flash[:alert] = "Error creating new User: #{@user.errors.messages}"
      redirect_to new_user_path
    else
      process_user_roles params
      redirect_to users_path
    end
  end

  def ghost_user
    session[:admin_user_id] = current_user.id
    usr = User.find(params[:id])
    sign_in(usr, bypass: true)
    session[:ghost_user] = usr.id
    redirect_to root_path
  end

  def un_ghost_user
    unless session[:admin_user_id].nil?
      user = User.find(session[:admin_user_id])
      sign_in(user, bypass: true)
      session[:admin_user_id] = nil
      session[:ghost_user] = nil
    else
      session[:admin_user_id] = nil
      session[:ghost_user] = nil
    end
    redirect_to root_path
  end

  def set_user_active
    arr = params['value'].split(',')

    user = User.find_by_id(arr[0])
    user.active_user = arr[1] == 'true'
    user.save
    render :json => {
        user: user
    }
  end

  def shift_print
    @user = User.find(params[:id])
  end

  def set_start_year
    if params[:year].nil?
      redirect_to :back, :alert => 'Error - no year set'
    else
      User.all.each do |u|
        u.start_year = params[:year]
        u.save
      end

      redirect_to :back, :notice => "All users set to start year of: #{params[:year]}"
    end
  end

  def clear_assignments
    Shift.all.each do |s|
      s.user_id = nil
      s.save
    end
    redirect_to :back, :notice => "All Shift Assignments Have Been Cleared"
  end

  def reset_confirms_and_passwords
    User.reset_all_accounts
    redirect_to :back, :notice => "All Users Have Been Reset..."
  end

  def init_confirmations
    User.active_users.each do |u|
      u.confirmed = false
      u.save
    end
    redirect_to :back, :notice => "All User Confirmations Have Been Reset..."
  end

  def init_meetings
    User.populate_meetings
    redirect_to :back, :notice => "All Meetings have been processed."
  end

  # def send_shift_reminder_email
  #   emailaddress = 'aamaxworks@gmail.com'
  #
  #   @subject = "REMINDER: you are scheduled to work at Snowbird tomorrow!"
  #   @fromaddress = 'no-reply@snowbirdhosts.com'
  #   @message = "Just a friendly reminder that you are scheduled to work a shift at the Bird tomorrow.  Don't be late!"
  #
  #   UserNotifierMailer.send_shift_reminder_email(emailaddress, @fromaddress, @subject, @message).deliver
  # end


  private
  def process_user_roles params
    return if !current_user.has_role? :admin
    if params['role'].nil?
      @user.roles = []
    else
      missing_roles = []
      extra_roles = []
      params['role'].each do |k, v|
        if !(@user.roles.map { |r| r.name }.include? k)
          missing_roles << k
        end
      end
      @user.roles.each do |r|
        if params['role'][r.name].nil?
          extra_roles << r.name
        end
      end
      extra_roles.each do |r|
        @user.remove_role r
      end
      missing_roles.each do |r|

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  street                 :string(255)
#  city                   :string(255)
#  state                  :string(255)
#  zip                    :string(255)
#  home_phone             :string(255)
#  cell_phone             :string(255)
#  alt_email              :string(255)
#  start_year             :integer
#  notes                  :text
#  confirmed              :boolean
#  active_user            :boolean
#  nickname               :string(255)
#  snowbird_start_year    :integer
#  head_shot              :string(255)
#

module UsersHelper

end

app/views/users/_confirmation_form.html.erb
<h1>Please Confirm Your Information</h1>
<%= form_for current_user,  :controller => 'users', html: {class: "nifty_form"} do |f| %>
    <%= f.hidden_field(:page_type, :value => 'confirmation_page') %>
    <% @user = current_user %>
    <%= render "/users/form", f: f %>
    <%= f.submit "Update", id: 'user_form_submit', class: 'btn btn-success' %>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="span4">
    <% if @user.head_shot.nil? || (@user.head_shot == '') %>
      <%=  gravatar_image_tag(@user.email, :alt => @user.name) %>
      <%= link_to "Setup Gravatar", "http://gravatar.com" %>
      <br/>

    <% else %>
      <%= image_tag @user.head_shot %>
    <% end %>
  </div>
  <div class="span5 well">
    <br/>
    <% if !@user.confirmed %>
      <h3>Be Sure You Are Confirmed!</h3><br/>
    <% end %>
    <strong>Confirmed? </strong>
    <%= f.check_box :confirmed, :placeholder => "confirmed", class: 'active_edit', :required => !current_user.has_role?(:admin) %><br/>

    <br/><br/>
    <%= f.password_field :password, class: 'password_edit', placeholder: 'Password', :autocomplete => :off %> <br/>
    <%= f.password_field :password_confirmation, class: 'password_edit', placeholder: 'Password Confirmation' %> <br/><br/>

    <%= f.submit "Update", id: 'user_form_submit', class: 'btn btn-success' %>
    <%= link_to "Cancel", users_path, class: "btn btn-warning" %>

    <br/><br/>
  </div>
</div>

<br/>
<br/>
<% if current_user.has_role? :admin %>
    <strong>Image Path/file: </strong> <%= f.text_field :head_shot,
                  :placeholder => "Headshot File", class: 'name_edit form-control' %><br/>
<% end %>

<strong>Name: </strong> <%= f.text_field :name, :placeholder => 'Name', class: 'name_edit form-control' %>
<strong>Nick Name: </strong> <%= f.text_field :nickname, :placeholder => 'NickName', class: 'name_edit form-control' %><br/>

<div class="form-group">
<strong>Address: </strong><br/>
<%= f.text_field :street, :placeholder => 'Street Name', class: 'street_edit form-control' %> <br/>
<%= f.text_field :city, :placeholder => 'City', class: 'city_edit form-control' %>,
<%= f.text_field :state, :placeholder => 'State', class: 'state_edit form-control' %>
<%= f.text_field :zip, :placeholder => 'Zip', class: 'zip_edit form-control' %>   <br/>
</div>

<strong>Home Phone: </strong>
<%= f.telephone_field :home_phone, :placeholder => 'Home Phone', class: 'phone_edit' %> <br/>
<strong>Cell Phone: </strong>
<%= f.telephone_field :cell_phone, :placeholder => 'Cell Phone', class: 'phone_edit' %> <br/>
<strong>Email: </strong>
<%= f.email_field :email, :placeholder => 'Email', class: 'email_edit', :autocomplete => :off %> <br/>
<strong>Alt Email: </strong>
<%= f.email_field :alt_email, :placeholder => 'Alternate Email', class: 'email_edit' %> <br/>

<% if current_user.has_role? :admin %>
    <strong>Active?: </strong>
    <%= f.check_box :active_user, :placeholder => "active", class: 'active_edit' %>
<% end %>

<% if current_user.has_role? :admin %>
    <br/>
    <strong>Notes: </strong><br/>
    <%= f.text_area :notes, class: 'notes_edit', placeholder: 'Admin Notes' %> <br/>

    <strong>Start Year: </strong>
    <%= f.text_field :start_year, :placeholder => 'Start Year', class: 'year_edit' %> <br/>
    <strong>Snowbird Start Year: </strong>
    <%= f.text_field :snowbird_start_year, :placeholder => 'Snowbird Start Year', class: 'year_edit' %>
<% else %>
    <strong>Start Year: </strong> <%= @user.snowbird_start_year %>
<% end %>
<br/>

<strong>seniority: </strong> <%= @user.seniority %><br/><br/>

    <% unless current_user.has_role? :admin %>
        <h5>Roles:</h5>
        <ul>
          <% @user.roles.each do |r| %>
              <li><%= r.name %></li>
          <% end %>

          <% if @user.roles.empty? %>
            <li>No Roles Defined...</li>
          <% end %>
        </ul>
    <% else %>
        <h5>Roles</h5>
        <ul>
          <% Role.all.each do |r| %>
              <% if @user.roles.include? r
                   role_checked = true
                 else
                   role_checked = false
                 end %>
              <li>
                <input title='Role on/off' id=<%= "role_#{r.name}" %> name=<%= "role[#{r.name}" %> type="checkbox" <%= role_checked ? 'checked' : '' %> />

                <%= r.name %>
              </li>
          <% end %>

        </ul>
    <% end %>
    <hr/>

<h5>shift summary info: </h5>
<table class='table table-striped'>
  <tr>
    <th>Date</th>
    <th>DOW</th>
    <th>Shift</th>
    <th>Status</th>
    <th>Tools</th>
  </tr>
    <% @user.get_working_shifts&.each do |s| %>
      <tr>
        <td><%= s.shift_date.strftime("%Y-%m-%d") %></td>
        <td><%= s.day_of_week %></td>
        <td><%= "#{s.shift_type.short_name[0..1]} - #{s.shift_type.description}" %></td>
        <td><%= s.shift_type.tasks %></td>
        <td>
          <% if s.class == OngoingTraining %>
            <% if s.can_drop current_user %>
              <%= link_to "<i class='icon-trash btn btn-danger' title='drop shift'>&nbsp;&nbsp;Drop</i>".html_safe,
                          "/drop_ongoing_training/#{s.id}",
                          :title => "Drop #{s.id}" %>
            <% end %>
          <% else %>
            <% if s.can_drop current_user %>
              <%= link_to "<i class='icon-trash btn btn-danger' title='drop shift'>&nbsp;&nbsp;Drop</i>".html_safe,
                          "/drop_shift/#{s.id}",
                          data: { :confirm => "You sure you want to drop this shift?" },
                          :title => "Clear Shift", :class=>'drop_shift_btn select_btn' %>
            <% end %>
          <% end %>

        </td>
      </tr>
    <% end %>



</table>
<br/>

app/views/users/_shift_entry_for_print.html.erb
<td class="col-sm-2 col-md-2">
  <% if object.shift_date.nil? %>
      UnSet
  <% else %>
      <%= shiftdate = object.shift_date.strftime("%a.  %m/%d/%Y") %>

  <% end %>
</td>

<td class="col-sm-3 col-md-3">
  <%=  "#{object.short_name[0..1]} - #{object.shift_type.description }" %>
</td>
<td class="col-sm-3 col-md-3">
  <%= "#{object.shift_type.start_time} - #{object.shift_type.end_time}" %>
</td>
<td class="col-sm-3 col-md-3">
  <%=   object.shift_type.tasks %>
</td>

app/views/users/_shift_message.html.erb
<div class='user_shift_message_box col-sm-4 col-md-4'>
  <h4>Selection Status
    <% if shift_page == false %>
        [<a href='<%= shifts_path %>'>Go To Shifts Page]</a>
    <% end %>
  </h4>
  <% user.shift_status_message.each do |m| %>
    <%= m.html_safe %>   <br/>
      <br/>
  <% end %>
  <br/>
</div>

app/views/users/_user_group_display.html.erb
<% collection.each do |u| %>
    <tr id=<%= "user_record_#{u.id}" %> class='user_entry' >
      <%= render 'user_index_entry', object: u %>
    </tr>
<% end %>

app/views/users/_user_index_entry.html.erb
<td class='centered'>
  <input type='hidden' value='<%= object.name %>'>

  <a href='<%= user_path(object) %>'>
    <%= "#{object.name}" %><br/>
    <% if object.head_shot.nil? || (object.head_shot == '') %>
         <%= gravatar_image_tag(object.email, :alt => object.name, class: "user_img") %>
    <% else %>
         <%= image_tag object.head_shot, :class => 'index_head_shot user_img' %>
    <% end %>

  </a> <br/>
  <%= link_to object.email, "send_mail/#{object.email}" %><br/>
  ID: <%= object.id %><br/>
</td>

<td>
  <strong>Address:</strong><br/>
  <%= object.street %> <br/>
  <%= object.city %>, <%= object.state %> <%= object.zip %><br/> <br/>
  <strong>Home Phone:</strong> <%= number_to_phone(object.home_phone) %><br/>
  <strong>Cell Phone:</strong> <%= number_to_phone(object.cell_phone) %>
</td>

<td>
  <strong>Scheduled Shifts: </strong><%= object.shifts.length %> <br/>
  <strong>Shifts Worked: </strong> <%= object.shifts_worked.length %> <br/><br/>
  <strong>Active:</strong>

  <% if current_user.admin? %>
    <%= check_box_tag("user_active_#{object.id}", "user_active_#{object.id}", object.active_user, :class => 'set_active') %>
  <% else %>
    <%= object.active_user %>
  <% end %>
  <br/><br/>

  <strong>Roles:</strong>
  <%= object.roles.map {|r| r.name }.join(", ") %>
  <br/>
</td>

<td>
  <strong>Start Date:</strong> <%= object.snowbird_start_year %> <br/>
  <strong>Seniority:</strong> <%= object.seniority %><br/>
  <strong>Last Signed In:</strong>
        <%= object.last_sign_in_at.nil? ? "---" :
              object.last_sign_in_at.in_time_zone("Mountain Time (US & Canada)").strftime("%Y-%m-%d %H:%M") %> <br/>
  <% if current_user.admin? && !object.notes.blank? %>
    <br/>
      <div class="user_notes_box">
        <strong>NOTES: </strong><br/>
        <%= object.notes %>
      </div>
  <% end %>
</td>

<td>
  <% if ((current_user.has_role? :admin) || (current_user.id == object.id)) %>
      <a href='<%= edit_user_path(object) %>'><i class='icon-wrench icon-large icon_blue icon_obj'></i></a>
      <% if (current_user.email == MAX_EMAIL) && (object.id != current_user.id)%>
          <a href="/ghost_user/<%= object.id %>"><i class="icon-user icon_blue icon-large icon_obj" title="Ghost This User"></i></a>
      <% end %>
      <a href='shift_logs/by_user/<%= object.id %>'>
        <i class='icon-search icon-large icon_blue icon_obj'></i>
      </a>
  <% end %>

  <% if ((current_user.has_role? :admin) && (object.id != current_user.id)) %>
      <a href='<%= user_path(object) %>' data-method='delete' data-confirm="You sure you want to delete this Host?" title='Delete Host'>
        <i class='icon-trash icon-large icon_red icon_obj'></i>
      </a>
  <% end %>

</td>

app/views/users/edit.html.erb
<%= form_for @user, url: {action: "update", method: :put}, html: {class: "nifty_form"} do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, url: {action: "create", method: :post}, html: {class: "nifty_form"} do |f| %>
    <%= render "form", f: f %>
    <%= f.submit "Save", id: 'user_form_submit', class: 'btn btn-success' %>
    <%= link_to "Cancel", users_path, class: "btn btn-warning" %>
<% end %>