config/routes.rb
Mthost::Application.routes.draw do
  resources :shift_logs
  devise_for :users

  resources :users
  resources :mail
  resources :shift_types
  resources :shifts
  resources :shift_collections
  resources :galleries
  resources :exports
  resources :sys_configs
  resources :reports
  resources :pages
  resources :host_haulers, only: [:index]
  resources :ongoing_trainings
  resources :training_dates
  resources :ongoing_trainings

  get '/download_end_of_year', :to =>  "exports#eoy_download"
  get '/export/shift_summary/:year', :to =>  "exports#shift_summary_download"
  get '/hosts_by_seniority', :to => 'users#hosts_by_seniority'
  get '/hosts_by_seniority_export', :to => 'reports#hosts_by_seniority_export' # only used with csv suffix
  get '/hosts_by_roles', :to => 'users#hosts_by_roles'
  get '/shifts_by_date', :to => 'shifts#shifts_by_date_view'
  get '/skipatrol', :to => "reports#skipatrol"
  post '/skipatrol', :to => "reports#skipatrol"
  get '/skipatrol_printable', :to => "reports#skipatrol_printable"

  get '/duties_report', :to => 'reports#duties_report'
  post '/duties_report', :to => 'reports#duties_report'
  get '/duties_printable', :to => "reports#duties_printable"
  get '/hauler_drivers_report', :to => "reports#hauler_drivers_report"

  get '/shift_print/:id', :to => 'users#shift_print'
  post '/users/save_new', :to => 'users#save_new'
  post '/shifts/assign_team_leaders', :to => 'shifts#assign_team_leaders'
  get '/assign_team_leaders', :to => 'shifts#edit_team_leader_shifts'

  # EMAIL STUFF
  get 'send_shift_reminder_email', :to => "mail#send_shift_reminder_email"
  get '/select_hosts_for_email', :to => "mail#select_hosts_for_email"

  get '/send_custom_mail', :to => "mail#send_custom_mail"
  post '/send_custom_mail', :to => "mail#send_custom_mail"
  post '/deliver_mail', :to => "mail#deliver_mail"
  get '/send_mail/:address', :to => "mail#send_mail"
  get '/send_mail/hauler/:hauler_id', :to => 'mail#send_hauler_mail'


  get '/show_contact_info', :to => "pages#show_contact_info"

  get '/set_start_year/:year', :to => "users#set_start_year"
  get '/clear_assignments', :to => "users#clear_assignments"
  get '/delete_shifts', :to => "shifts#delete_shifts"
  get '/delete_hauler_entries', :to => "host_haulers#delete_all_entries"
  get '/reset_confirms_and_passwords', :to => "users#reset_confirms_and_passwords"
  get '/init_confirmations', :to => "users#init_confirmations"
  get '/init_meetings', :to => "users#init_meetings"


  post '/set_user_active/:value', :to => "users#set_user_active"

  get '/drop_shift/:id', :to => 'shifts#drop_shift'
  get '/select_shift/:id', :to => 'shifts#select_shift'
  # get '/disable_shift/:id', :to => 'shifts#toggle_shift_disabled' #'shifts#disable_shift'
  # get '/enable_shift/:id', :to => 'shifts#toggle_shift_disabled' #'shifts#enable_shift'
  # get '/toggle_shift_disabled/:id', :to => 'shifts#toggle_shift_disabled'
  post '/toggle_shift_disabled/:value', :to => 'shifts#toggle_shift_disabled'

  get '/ghost_user/:id', :to => 'users#ghost_user'
  get '/un_ghost_user', :to => 'users#un_ghost_user'

  get "shift_logs/by_shift/:shift_id", :to => 'shift_logs#by_shift'
  get "shift_logs/by_user/:user_id", :to => 'shift_logs#by_user'

  get '/hauler_scheduler/:hauler_id', :to => 'host_haulers#scheduler'

  get '/drop_driver/:id', :to => 'host_haulers#drop_driver'
  get '/select_driver/:id', :to => 'host_haulers#select_driver'

  get '/drop_rider/:rider_id', :to => 'host_haulers#drop_rider'
  get '/select_rider/:rider_id', :to => 'host_haulers#select_rider'
  get '/export_hauler/:hauler_id', :to =>  "exports#host_hauler_download"
  get '/set_rider_to_host/:rider_id', :to => 'host_haulers#set_rider_to_host'
  post '/update_rider_in_hauler', :to => 'host_haulers#update_rider_in_hauler'
  get '/set_driver_to_host/:hauler_id', :to => 'host_haulers#set_driver_to_host'
  post '/update_driver_in_hauler', :to => 'host_haulers#update_driver_in_hauler'
  get '/add_hauler/:date_value', :to => 'host_haulers#add_hauler'
  get '/hauler_scheduler', :to => 'host_haulers#scheduler'
  get '/delete_hauler/:hauler_id', :to => 'host_haulers#delete_hauler'
  get '/drop_ongoing_training/:id', :to => 'ongoing_trainings#drop_shift'
  get '/select_ongoing_training', :to => 'ongoing_trainings#select_ongoing_training'
  post '/make_ongoing_training_selection/:is_trainer/:id', :to => 'ongoing_trainings#make_ongoing_training_selection'

  # catchall route to get pages
  get "/:id" => "pages#show"
  root :to => "pages#show"
end

app/models/shift_type.rb
# == Schema Information
#
# Table name: shift_types
#
#  id          :integer          not null, primary key
#  short_name  :string(255)      not null
#  description :string(255)      not null
#  start_time  :string(255)
#  end_time    :string(255)
#  tasks       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ShiftType < ActiveRecord::Base
  attr_accessible :short_name, :description, :start_time, :end_time, :tasks

  #time_regex = /[0-1][0-9]:[0-6][0-9]/

  validates   :short_name, :presence => true, :length   => { :maximum => 20 }
  validates   :description, :presence => true, :length   => { :maximum => 255 }
  #validates   :start_time, :presence => true, :format => { :with => time_regex }
  #validates   :end_time, :presence => true, :format => { :with => time_regex }
  validates   :tasks, :length   => { :maximum => 255 }

  #has_many    :shifts, :dependent => :destroy
  #
  #default_scope :order => "shortname"
  #scope :distinctShifttypes, :select => ('distinct shortname')
  scope :meetings, -> {where("short_name ilike 'M%'").order(:short_name)}

  def self.team_lead_type
    ShiftType.where("short_name in ('TL')")
  end

  def is_tour?
    !/(P[1-4]|ST)/.match(self.short_name).nil?
    # self.tasks.nil? ? false : self.tasks.downcase.include?('tour')
  end

  def is_working?
    self.short_name[0] != 'M'
  end

  def abbreviated_name
    self.short_name[0..1]
  end

end

app/controllers/shifts_controller.rb
# == Schema Information
#
# Table name: shifts
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  shift_type_id   :integer          not null
#  shift_status_id :integer          default(1), not null
#  shift_date      :date
#  day_of_week     :string(255)
#  day_of_week     :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  short_name      :string
#  disabled        :boolean
#

class ShiftsController < ApplicationController
  require "json"
  authorize_resource
  load_resource :except => [:index]

  respond_to :html, :json, :js

  def index
    @days = DAYNAMES.map{|u| ["#{u}", "#{u[0...3]}"]}
    @shift_types = ShiftType.uniq.pluck(:short_name).to_a.sort {|a,b| a <=> b }
        # ShiftType.all.map {|st| st.short_name[0..1] }.uniq.sort {|a,b| a <=> b }
    @users = User.active_users.pluck(:name).sort #map{|u| ["#{u.name}"]}.sort
    per_page = SysConfig.first.shift_count
    per_page ||= 100

    @return_params = {"start_from_today" => true, "show_shifts_expanded" => false, "show_only_unselected" => false,
                      "show_only_holidays" => false, "include_meeting_shifts" => false,
                      "show_only_shifts_i_can_pick" => !current_user.has_role?(:admin),
                      "shift_types_to_show" => "", 'days_of_week_to_show' => {},
                      "hosts_to_show" => {}, "date_set_to_show" => '',
                      "date_for_calendar" => Date.today.strftime("%Y-%m-%d")
    }

    unless params['filter'].nil?
      form_filters = params['filter']
    end
    form_filters ||= {"start_from_today" => '1',
                          "shifts_i_can_pick" => current_user.has_role?(:admin) ? '0' : '1',
                          'shifttype' => "", 'dayofweek' => {}, "hosts" => {},
                          "date" => '', "date_for_calendar" => Date.today.strftime("%Y-%m-%d")
    }

    @shifts = Shift.get_shifts_for_index(current_user, @return_params,
      form_filters).paginate(:page => params[:page], :per_page => per_page)
    @shifts
  end

  def destroy
    shift = Shift.find(params[:id])
    shift_user_name = shift.user.name unless shift.user.nil?
    log_shift_dropped(shift, current_user) unless shift.user.nil?

    shift_details = "ID: #{shift.id} Date:#{shift.shift_date.strftime("%Y-%m-%d")} Shortname:#{shift.short_name} HOST: #{shift_user_name}"

    if !Shift.destroy(params[:id])
      flash[:alert] = "Error destroying shift."
      log_shift_destroy(params[:id], "failed to delete: #{shift_details}", current_user)
    else
      log_shift_destroy(params[:id], "success deleting shift: #{shift_details}", current_user)
    end
    redirect_to :back
  end

  # def disable_shift
  #   s = Shift.find(params[:id])
  #   s.disabled = true
  #   s.save
  #
  #   log_shift_enabled_or_disabled(s, current_user)
  #   redirect_to :back
  # end
  #
  # def enable_shift
  #   s = Shift.find(params[:id])
  #   s.disabled = false
  #   s.save
  #
  #   log_shift_enabled_or_disabled(s, current_user)
  #
  #   redirect_to :back
  # end

  def toggle_shift_disabled
    arr = params['value'].split(',')
    s = Shift.find(arr[0])
    s.disabled = (arr[1] == 'false')
    s.save
    log_shift_toggle_disabled(s, current_user)

    render :json => {
        shift: s
    }
  end

  def drop_shift
    s = Shift.find(params[:id])
    log_shift_dropped(s, current_user)
    s.user_id = nil
    s.save

    send_shift_change_email('dropped', s)
    redirect_to :back
  end

  def select_shift
    s = Shift.find(params[:id])
    if s.user_id.nil?
      s.user_id = current_user.id
      s.save
      log_shift_selected(s, current_user)
    else
      redirect_to "/shifts", :alert => "Sorry - this shift has already been taken. Please try a different shift"
      return
    end

    send_shift_change_email('selected', s)

    redirect_to :back
  end

  def edit
    if ((@shift.user_id == current_user.id) || (current_user.has_role? :admin)  || @shift.user_id.nil?)
      @title = "Edit Shift"
      @shift.user_id.nil? ? @user_name = "UnSet" : @user_name = @shift.user.name
      @userlist = User.active_users
      if (current_user.has_role? :admin)
          if @shift.meeting?
            # trim all users who are in a meeting on this day out of list
            shift_users = Shift.where("shift_date = ? and shift_type_id = ?", @shift.shift_date, @shift.shift_type_id).map { |s| s.user}
          else
            # trim all users who are working already (non meeting) for that day out of list
            shift_users = Shift.where("shift_date = ? and short_name not like 'M%'", @shift.shift_date).map { |s| s.user}
          end

          @userlist = @userlist - shift_users
          @userlist.sort! { |a,b| a.name <=> b.name }
      else
        @userlist = [current_user]
      end
    else
      redirect_to shifts_path
    end
  end

  def update
    previous_user_id = @shift.user_id
    if @shift.update_attributes(params[:shift])
      flash[:success] = "Shift updated."
      log_shift_update(previous_user_id, @shift, current_user)
      redirect_to shifts_path #+ "?" + strParams

      send_shift_change_email('updated', @shift)

      return
    else
      @title = "Edit Shift"
      flash[:failure] = "ERROR: shift not updated. #{@shift.errors.messages}"
      log_shift_failed_update(previous_user_id, @shift, params[:shift], current_user)
      render 'edit'
      return
    end

    # TODO add code to preserve params for shifts index filter
    #@params = {:filter=>params[:shift][:filter]}.to_param unless params[:shift].nil?
    #@params ||= {:filter=>params[:filter]}.to_param
    #
    #params[:shift].delete(:filter) unless params[:shift].nil?
    #
    #strParams = ""
    #if !params[:page].blank?
    #  strParams = "page=" + params[:page]
    #  unless @params.blank?
    #    strParams += "&"
    #  end
    #end
    #strParams += @params
    #
    #if (params[:status].blank?)
    #  # update from edit form
    #  if ((@shift.user_id == current_user.id) || (current_user.has_role? :admin) ||
    #      (@shift.user_id.nil?))
    #    if @shift.update_attributes(params[:shift])
    #      flash[:success] = "Shift updated."
    #
    #      redirect_to shifts_path + "?" + strParams
    #      return
    #    else
    #      @title = "Edit Shift"
    #      flash[:failure] = "ERROR: shift not updated."
    #      render 'edit'
    #      return
    #    end
    #  else
    #    redirect_to shifts_path + "?" + strParams
    #    return
    #  end
    #else
    #  if (params[:status] == "clear")
    #    # clear shift
    #    clear_shift_host(@shift.id)
    #    flash[:success] = "Shift Cleared..."
    #  elsif (params[:status] == "select")
    #    # make sure i can still select this shift
    #    unless can_i_pick_this_shift(current_user, @shift)
    #      flash[:failure] = "You do not have permissions to select this shift."
    #    else
    #      # select shift
    #      select_shift_host(@shift.id, current_user.id)
    #      flash[:success] = "Shift Selected..."
    #    end
    #  elsif (params[:status] == "Worked")
    #    # to worked 1
    #    update_shift_status(@shift.id, 1)
    #    flash[:success] = "Shift Status Set To Worked..."
    #  elsif (params[:status] == "Missed")
    #    # to missed -1
    #    update_shift_status(@shift.id, -1)
    #  end
    #
    #  redirect_to shifts_path + "?" + strParams
    #end
  end

  def delete_shifts
    Shift.delete_all
    redirect_to :back, :notice => "All Shifts Have Been Deleted"
  end

  def shifts_by_date_view
    if params[:date] == ""
      params[:date] = nil
    end

    if params[:date]
      @datevalue = params[:date].to_date
      @shifts = Shift.where("shift_date = ?", @datevalue).includes(:user).order('users.name')

      #if @datevalue >= HostSite::season_start
      #  @shifts = Shift.where("shift_date = ?", params[:date])
      #else
      #  @shifts = Shift.unscoped.where("shift_date = ?", params[:date])
      #end

      #elsif params[:filter][:date]
      #@shifts = Shift.where("shift_date = ?" params[:filter][:date])

    elsif !params[:filter]
      @datevalue = Date.today

      @shifts = []
    end
  end

  def edit_team_leader_shifts
    @leaders = User.with_role(:team_leader).to_a.delete_if {|u| !u.active_user}
    render 'edit_team_leader_shifts'
  end

  def assign_team_leaders
    Shift.assign_team_leaders(params)
    redirect_to shifts_path # TODO just show TL shifts
  end

  private
  def log_shift_destroy(shift_id, result_msg, user)
    ShiftLog.create(change_date: DateTime.now, user_id: user.id,
                  shift_id: shift_id, action_taken: "Delete Shift", note: result_msg)
  end

  def log_shift_dropped(shift, user_dropping)
    shift_str = "#{shift.id}:#{shift.short_name}:#{shift.shift_date}"
    log_user = user_dropping
    if user_dropping != shift.user
      log_user = shift.user unless shift.user.nil?
      ShiftLog.create(change_date: DateTime.now, user_id: user_dropping.id,
                      shift_id: shift.id, action_taken: "Dropped Shift",
                      note: "#{user_dropping.name} DROPPED shift #{shift_str} for user: #{shift.user.name} dropped by: #{user_dropping.name}")
    end
    ShiftLog.create(change_date: DateTime.now, user_id: log_user.id,
                    shift_id: shift.id, action_taken: "Dropped Shift",
                    note: "#{user_dropping.name} DROPPED shift #{shift_str} for user: #{shift.user.name} dropped by: #{user_dropping.name}")
  end

  def log_shift_toggle_disabled(shift, user)
    # must be admin
    if user.admin?
      shift_user = shift.user.nil? ? '---' : shift.user.name
      shift_str = "#{shift.id}:#{shift.short_name}:#{shift.shift_date}:assigned:#{shift_user}"
      ShiftLog.create(change_date: DateTime.now, user_id: user.id,
                      shift_id: shift.id, action_taken: "Toggle Shift Disabled Flag",

app/helpers/shifts_helper.rb
# == Schema Information
#
# Table name: shifts
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  shift_type_id   :integer          not null
#  shift_status_id :integer          default(1), not null
#  shift_date      :date
#  day_of_week     :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  short_name      :string
#  disabled        :boolean
#

module ShiftsHelper
  def getShiftTotal(adate)
    Shift.where("shift_date = ?", adate).count
  end

  def getSelectedShifts(adate)
    Shift.where("shift_date = ? and user_id is null and ((disabled = false) OR (disabled is NULL))", adate).count
  end
end

app/views/shifts/_form.html.erb
<% params[:filter].each do |key, value| %>
    <%= f.hidden_field "filter[#{key}]", :value => value %>
<% end if params[:filter] %>

<%= render 'shared/error_messages', :object => f.object %>
<br />
<div class="field">
  <%= f.label "Host: " %>
  <%= collection_select(:shift, :user_id,
                        @userlist, :id, :name,
                        options = {:selected => @shift.user_id.to_i, :prompt => "UnSet", class: "form-control"})
  %>
</div>

<div class="row">
  <div class= "span2">
    <strong>Shift Date: </strong>
  </div>
  <div class="span3">
    <%= @shift.shift_date %>
  </div>
</div>
<br/>

<div class="row">
  <div class= "span2">
    <strong>Shift Name: </strong>
  </div>
  <div class="span3">
    <%= @shift.shift_type.short_name[0..1] %>
  </div>
</div>
<br/>

<div class="row">
  <div class= "span2">
    <strong>Description: </strong>
  </div>
  <div class="span3">
    <%= @shift.shift_type.description %>
  </div>
</div>
<br/>

<div class="row">
  <div class= "span2">
    <strong>Start Time: </strong>
  </div>
  <div class="span3">
    <%= @shift.shift_type.start_time %>
  </div>
</div>
<br/>

<div class="row">
  <div class= "span2">
    <strong>End Time: </strong>
  </div>
  <div class="span3">
    <%= @shift.shift_type.end_time %>
  </div>
</div>
<br/>

<div class="row">
  <div class= "span2">
    <strong>Notes: </strong>
  </div>
  <div class="span3">
    <%= @shift.shift_type.tasks %>
  </div>
</div>
<br/>

app/views/shifts/_shifts_by_date_view_entry.html.erb
<td>
  <%= object.shift_date.strftime("%a.  %m-%d-%Y") %>
</td>
<td>
  <% if object.user_id.nil? %>
      UnSet
  <% else %>
      <%= user = User.find(object.user_id)
          user.name
      %>
  <% end %>

</td>

<td>
  <%=
      object.short_name
  %>
</td>

<td>
  <%= object.shift_type.description %>
</td>
<td>
  <%= object.shift_type.tasks %>
</td>

app/views/shifts/edit.html.erb
<h1><%= "#{@title}" %></h1>

<%= form_for(@shift) do |f| %>
    <%= render "form", :f => f %>

    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
<% end %>

app/views/shifts/index.archive.html.erb
<h1>Snowbird Mountain Host: Shifts</h1>

<div class="shift_page_header">
  <div class="shift_page_filter">
    <%= will_paginate(@shifts, :renderer => 'BootstrapPaginationHelper::LinkRenderer') %>

    <div class='row'>
      <div class='span4'>
        <% if current_user.has_role? :admin %>
          <button type="button" class="btn" data-toggle="collapse" data-target="#stats_display">
            Open Stats:&nbsp;&nbsp;<i class='icon-collapse icon-large icon-white'></i>
          </button>
        <% end %>
        <button type="button" class="btn" data-toggle="collapse" data-target="#shift_filter">
          Open Filter:&nbsp;&nbsp;<i class='icon-collapse icon-large icon-white'></i>
        </button>
      </div>
    </div>
    <div id="shift_filter" class="collapse out">
      <%= render "shifts/filter/shift_filter_form" %>
    </div>

    <div id="stats_display" class="collapse <%= current_user.shift_status_message.length > 0 ? "in" : "out" %>">
      <% if current_user.has_role? :admin %>
        <div class='row'>
          <div class='span5'>
            <h4>Shift Stats:</h4>
            <strong>Total Shifts:</strong>  <%= Shift.all.length %><br/>
            <strong>Assigned Shifts:</strong>   <%= Shift.assigned.length %><br/>
            <strong>Open Shifts:</strong><br/>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;All Year: <%= Shift.un_assigned.length %>
            <br/>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;From
            Today: <%= Shift.un_assigned.to_a.delete_if { |s| s.shift_date < Date.today }.length %><br/>
          </div>
        </div>
      <% end %>
      <div class='row'>

        <% unless current_user.supervisor? %>
          <%= render "/users/shift_message", :user => current_user, :shift_page => true %>
          <%= render "/users/selection_list", :user => current_user %>
        <% end %>
      </div>
    </div>

  </div>
</div>
<br/>

<%
  curr_date = ""
%>

<div class="shift_page_body">
  <% @shifts.includes(:user).includes(:shift_type).each do |s| %>

    <% if curr_date != s.shift_date %>
      <% if curr_date != '' %>
        </table>
        </div>
      <% end %>

      <button type="button" class="btn shift_button" data-toggle="collapse"
              data-target=<%= "#date_#{curr_date}" %>>
        <%= "#{s.shift_date.strftime("%a")} - #{s.shift_date} &nbsp;&nbsp;-&nbsp;&nbsp;Total:
                #{getShiftTotal(s.shift_date)} / Available: #{getSelectedShifts(s.shift_date)}".html_safe %>
      </button>
      &nbsp;&nbsp;&nbsp;
      <a href="/send_mail/THIS_DATE/?date=<%= s.shift_date %>" class='btn btn-info btn-small'>
        <i class='icon-envelope'></i> &nbsp;&nbsp;&nbsp; eMail Hosts Working This Day
      </a>

      <br/>

      <div id='<%= "date_#{curr_date}" %>' class="collapse <%= @return_params['show_shifts_expanded'] == true ? "in" : "out" %>">
        <table class='table table-striped'>
          <tr>
            <th>Host</th>
            <th>Select/Drop</th>
            <th>Code</th>
            <th>Description</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Notes</th>
            <th>Admin</th>
          </tr>
    <% end %>



    <tr>
      <td>
        <% unless s.user_id.nil? %>
          <a href=<%= user_path(s.user_id) %>><%= s.user.name %></a>
        <% end %>
      </td>

      <td class="align-left">
        <% if (@return_params['show_only_shifts_i_can_pick'] || !@return_params['selectable_shifts'][s.id].nil?) %>
          <a href=<%= "select_shift/#{s.id}/?test=hello" %> class='select_btn'>
            <i class="icon-male btn btn-primary" title="select shift">&nbsp;&nbsp;Select</i>
          </a>
        <% end %>

        <% if (s.can_drop(current_user) == true) %>
          <a href=<%= "drop_shift/#{s.id}" %> class='select_btn'><i class="icon-trash btn btn-danger" title="drop shift">&nbsp;&nbsp;Drop</i></a>
        <% end %>
      </td>

      <td class="align-center"><%= s.shift_type.short_name[0..1] %></td>
      <td><%= s.shift_type.description %></td>
      <td class="align-center"><%= s.shift_type.start_time %></td>
      <td class="align-center"><%= s.shift_type.end_time %></td>
      <td><%= s.shift_type.tasks %></td>

      <td class="align-center">
        <% if current_user.has_role? :admin %>
          <a href=<%= edit_shift_path(s.id) %>><i class="icon-wrench btn btn-info"
                                                  title="edit shift"></i></a>

          <%= link_to "<i class='icon-trash btn btn-danger'></i>".html_safe, s, :method => :delete,
                      data: { :confirm => "You sure you want to delete this shift?" },
                      :title => "Delete #{s.id}" %>

          <%= link_to "<i class='icon-search btn btn-primary'></i>".html_safe,
                      "shift_logs/by_shift/#{s.id}",
                      :title => "Show Logs For This Shift" %>

          <% if s.disabled? %>
            <%= link_to "<i class='icon-lock btn btn-default'></i>".html_safe,
                        "/enable_shift/#{s.id}",
                        :title => "Enable Shift" %>
          <% else %>
            <%= link_to "<i class='icon-ban-circle btn btn-warning'></i>".html_safe,
                        "/disable_shift/#{s.id}",
                        :title => "Disable Shift" %>
          <% end %>

        <% end %>
      </td>
    </tr>


    <% if curr_date != s.shift_date %>
      <% curr_date = s.shift_date %>
    <% end %>
  <% end %>

  <% if @shifts.length > 0 %>
    </table>
    </div>
  <% end %>

  </div>
  <br/>


  <div class="shift_page_footer">
    <hr/>
    <%= will_paginate(@shifts, :renderer => 'BootstrapPaginationHelper::LinkRenderer') %>
  </div>

app/views/shifts/shifts_by_date_view.html.erb
<h1>Shifts For Date: <%= @datevalue %></h1>

<%= form_for(:filter, :url => shifts_by_date_path, :method => :get) do |f|  %>
    <div id="filter_form">
      <table class="indexmenutable">
        <tr>
          <td>
            Date&nbsp;&nbsp;
          </td>
          <td>
            <%= text_field_tag(:date, @datevalue, :size => 20, :readonly=>'readonly', :class=>'shift_date', :id =>'filter_date') %>
          </td>
          <td>

            <%=  link_to "<i class='icon-calendar'></i>".html_safe, "#", :class=>"btn cal_icon",
                         :id=>"set_date_btn", :title => 'set date',
                         "data-date-format"=>"yyyy-mm-dd",
                         "data-date"=>@datevalue.strftime('%Y-%m-%d') %>

          </td>
          <td>
            <div class="actions">
              <%= f.submit('Apply Filter') %>
            </div>
          </td>
        </tr>
      </table>
    </div>

<% end %>

<% if @shifts.length == 0 %>
    <h3>No Shifts Scheduled for <%= @datevalue.strftime('%Y-%m-%d') %></h3>
<% end %>

<table class="table table-striped table-bordered table-condensed">
  <tr class="row">
    <th>Date</th>
    <th>HOST</th>
    <th>Shift</th>
    <th>Description</th>
    <th>Tasks</th>

  </tr>
  <% @shifts.each do |object| %>
      <tr class="row">

        <%=
            render "shifts_by_date_view_entry", :object => object %>

      </tr>
  <% end %>
</table>